name: Echo GitHub Secret Example

on:
  push:
    branches:
      - main

jobs:
  echo-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use GitHub Secret
        env:
          MY_SECRET: ${{ secrets.RESOURCE_NAME }}
        run: |
          echo "Using secret without exposing it"
          echo "The secret's length is: ${#MY_SECRET}" # Example usage without revealing it
