name: Echo GitHub Secret Example

on:
  workflow_dispatch:
    inputs:
      subscriptionId:
        description: "The Azure subscription ID"
        required: true
        type: string
      resourceGroup:
        description: "The Azure resource group name"
        required: true
        type: string
      resourceType:
        description: "The Azure resource type"
        required: true
        type: string
      resourceName:
        description: "The Azure resource name"
        required: true
        type: string

jobs:
  echo-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use GitHub Secret
        env:
          MY_SECRET: ${{ secrets.RESOURCE_NAME }}
        run: |
          echo "Using secret without exposing it"
          echo "The secret's length is: ${#MY_SECRET}" # Example usage without revealing it

      - name: Echo Inputs
        run: |
          echo "Subscription ID: ${{ github.event.inputs.subscriptionId }}"
          echo "Resource Group: ${{ github.event.inputs.resourceGroup }}"
          echo "Resource Type: ${{ github.event.inputs.resourceType }}"
          echo "Resource Name: ${{ github.event.inputs.resourceName }}"
